export const USER_INFO = [
  {
    id: 1,
    name: "Christyl Joy Reyes",
    position: "Front End Developer",
    date: "July 2018",
    status: "Active",
    role: "Owner",
  },
  {
    id: 2,
    name: "Christyl Joy Reyes",
    position: "Front End Developer",
    date: "July 2018",
    status: "Active",
    role: "Owner",
  },
  {
    id: 3,
    name: "Christyl Joy Reyes",
    position: "Front End Developer",
    date: "July 2018",
    status: "Active",
    role: "Owner",
  },
  {
    id: 4,
    name: "Christyl Joy Reyes",
    position: "Front End Developer",
    date: "July 2018",
    status: "Active",
    role: "Owner",
  },
  {
    id: 5,
    name: "Christyl Joy Reyes",
    position: "Front End Developer",
    date: "July 2018",
    status: "Active",
    role: "Owner",
  },
  {
    id: 6,
    name: "Christyl Joy Reyes",
    position: "Front End Developer",
    date: "July 2018",
    status: "Active",
    role: "Owner",
  },
  {
    id: 7,
    name: "Christyl Joy Reyes",
    position: "Front End Developer",
    date: "July 2018",
    status: "Active",
    role: "Owner",
  },
  {
    id: 8,
    name: "Christyl Joy Reyes",
    position: "Front End Developer",
    date: "July 2018",
    status: "Active",
    role: "Owner",
  },
  {
    id: 9,
    name: "Christyl Joy Reyes",
    position: "Front End Developer",
    date: "July 2018",
    status: "Active",
    role: "Owner",
  },
  {
    id: 10,
    name: "Christyl Joy Reyes",
    position: "Front End Developer",
    date: "July 2018",
    status: "Active",
    role: "Owner",
  },
];
